import { t } from "@/locales";

export const analysisResultCopy = {
  actions: {
    refresh: t("analysisV11.actions.refresh"),
    downloadReportZip: t("analysisV11.actions.downloadReportZip"),
  },
  summary: {
    title: t("analysisV11.summary.title"),
    description: t("analysisV11.summary.description"),
    fieldTableTitle: t("analysisV11.summary.fieldTableTitle"),
    fieldTableDescription: t("analysisV11.summary.fieldTableDescription"),
    noFieldTableSummary: t("analysisV11.summary.noFieldTableSummary"),
    topRiskTypes: t("analysisV11.summary.topRiskTypes"),
    topRuleTypes: t("analysisV11.summary.topRuleTypes"),
    topAffectedFiles: t("analysisV11.summary.topAffectedFiles"),
    noAffectedFiles: t("analysisV11.summary.noAffectedFiles"),
    dependencySummaryTitle: t("analysisV11.summary.dependencySummaryTitle"),
    noDependencySummary: t("analysisV11.summary.noDependencySummary"),
    fieldsBadge: (count: number) => t("analysisV11.summary.fieldsBadge", { count }),
    fieldStats: (readCount: number, writeCount: number, referenceCount: number) =>
      t("analysisV11.summary.fieldStats", { readCount, writeCount, referenceCount }),
    confidenceTitle: t("analysisV11.summary.confidenceTitle"),
    confidenceDescription: t("analysisV11.summary.confidenceDescription"),
    confidenceUnavailable: t("analysisV11.summary.confidenceUnavailable"),
    lowConfidenceTitle: t("analysisV11.summary.lowConfidenceTitle"),
    lowConfidenceDescription: t("analysisV11.summary.lowConfidenceDescription"),
    noMajorPenalties: t("analysisV11.summary.noMajorPenalties"),
  },
  warning: {
    title: t("analysisV11.warning.title"),
    sampleFileLabel: t("analysisV11.warning.sampleFileLabel"),
    displayedSampleFiles: (displayed: number, total: number) => t("analysisV11.warning.displayedSampleFiles", { displayed, total }),
    noDetails: t("analysisV11.warning.noDetails"),
  },
  risk: {
    empty: t("analysisV11.risk.empty"),
    unknownSource: t("analysisV11.risk.unknownSource"),
    noDescription: t("analysisV11.risk.noDescription"),
    recommendation: (text: string) => t("analysisV11.risk.recommendation", { text }),
    occurrence: (count: number) => t("analysisV11.risk.occurrence", { count }),
    affectedFiles: (count: number) => t("analysisV11.risk.affectedFiles", { count }),
  },
  rule: {
    empty: t("analysisV11.rule.empty"),
    unknownSource: t("analysisV11.rule.unknownSource"),
    recommendation: (text: string) => t("analysisV11.rule.recommendation", { text }),
    occurrence: (count: number) => t("analysisV11.rule.occurrence", { count }),
    affectedFiles: (count: number) => t("analysisV11.rule.affectedFiles", { count }),
  },
  dependency: {
    hiddenStandardLibrary: (count: number) => t("analysisV11.dependency.hiddenStandardLibrary", { count }),
    internalCount: (count: number) => t("analysisV11.dependency.internalCount", { count }),
    standardLibraryCount: (count: number) => t("analysisV11.dependency.standardLibraryCount", { count }),
  },
  pagination: {
    summary: (total: number, page: number, pageCount: number) => t("analysisV11.pagination.summary", { total, page, pageCount: Math.max(pageCount, 1) }),
    previous: t("analysisV11.pagination.previous"),
    next: t("analysisV11.pagination.next"),
  },
  toasts: {
    analysisQueued: t("analysisV11.toasts.analysisQueued"),
    analysisQueueFailed: t("analysisV11.toasts.analysisQueueFailed"),
    reportDownloadSucceeded: t("analysisV11.toasts.reportDownloadSucceeded"),
    reportDownloadFailed: t("analysisV11.toasts.reportDownloadFailed"),
    historicalReportDownloadSucceeded: t("analysisV11.toasts.historicalReportDownloadSucceeded"),
    historicalReportDownloadFailed: t("analysisV11.toasts.historicalReportDownloadFailed"),
    diffDownloadSucceeded: t("analysisV11.toasts.diffDownloadSucceeded"),
    diffDownloadFailed: t("analysisV11.toasts.diffDownloadFailed"),
    baselineUpdated: t("analysisV11.toasts.baselineUpdated"),
    baselineUpdateFailed: t("analysisV11.toasts.baselineUpdateFailed"),
    baselineCleared: t("analysisV11.toasts.baselineCleared"),
    baselineClearFailed: t("analysisV11.toasts.baselineClearFailed"),
  },
} as const;
